### ISSUE TITLE
Non symmetric matching

### ISSUE THREAD

**Issue by umairzahmed** [iradicek/clara#15]
Sometimes, matching code-X with code-Y will return success, but matching code-Y with code-X might return failure. Example:

```
$ cat temp1.c
#include<stdio.h>

int main(){
  int n, temp;
  scanf("%d", &n);
  
  temp = n;
  printf ("%d",t);
  return 0;
}

$ cat temp2.c
#include<stdio.h>

int main(){
  int n;
  scanf("%d", &n);


  printf("%d", n);
  return 0;
}

$ clara match temp2.c temp1.c --entryfnc "main" --ins "[[3]]"
Match!

$ clara match temp1.c temp2.c --entryfnc "main" --ins "[[3]]"
No match!
```

**Comment by iradicek** [comment]
I fixed this so that they do not match in any direction. The reason why the first invocation produced a match was because in CLI by default we allowed that the second program has more variables. Now the default is that they both have to have the same number of variables. The old behaviour can be still achieved by using CLARA as a library.
